# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 128
  max-buffers: 512
  buffer-size-mb: 128

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: azsussc
  account-key: arfNxv4j360fnxgipU0zYpoyCwVQANS8Pws+592T5qfSiiFfBVs1JNZhE5Vovw45SwdpdYqZeEAY+Z7jzn7/gg==
  endpoint: https://azsussc.blob.core.windows.net
  mode: key
  container: robotdata